name: Django CI

on:
  push:
    branches: [main]

jobs:
  sonarcloud:
    name: Sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: Sonarcloud Scan
        #uses: sonarsource/sonarqube-scan-action@v5.0.0
        uses: sonarsource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Clear cache
        run: |
          rm -rf ~/.sonar
          rm -rf .sonar
  #update
